CREATE TABLE produtos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ean VARCHAR(50) UNIQUE,
    descritivo VARCHAR(255),
    unidade_venda VARCHAR(20),
    politica VARCHAR(50),
    custo DECIMAL(15,4),
    pmz DECIMAL(15,4),
    venda DECIMAL(15,4),
    depto VARCHAR(50),
    secao VARCHAR(50),
    grupo VARCHAR(50),
    subgrupo VARCHAR(50),
    classificacao_fiscal VARCHAR(20),
    piscopins VARCHAR(20),
    monofasico VARCHAR(20),
    cest VARCHAR(20),
    tributacao_venda VARCHAR(50),
    icms_venda VARCHAR(20),
    st_venda VARCHAR(20),
    reducao_venda VARCHAR(20),
    iva VARCHAR(20),
    fcp VARCHAR(20),
    ipi VARCHAR(20),
    categoria_fiscal VARCHAR(50),
    -- Campos da revisão
    descricao VARCHAR(255),
    ncm VARCHAR(20),
    aliquota_ipi VARCHAR(20),
    cst_ipi VARCHAR(20),
    cst_pis_cofins_entrada VARCHAR(20),
    cst_pis_cofins_saida VARCHAR(20),
    codigo_sped VARCHAR(20),
    aliquota_pis VARCHAR(20),
    aliquota_cofins VARCHAR(20),
    base_legal_pis_cofins VARCHAR(255),
    cfop VARCHAR(20),
    cst_csosn VARCHAR(20),
    ad_rem_icms VARCHAR(20),
    aliquota_icms VARCHAR(20),
    aliquota_red_base_calculo_icms VARCHAR(20),
    situacao_tributaria VARCHAR(50),
    red_base_calculo_icms VARCHAR(20),
    red_base_calculo_icms_st VARCHAR(20),
    aliquota_icms_st VARCHAR(20),
    iva_mva VARCHAR(20),
    fcp_revisao VARCHAR(20),
    cod_beneficio_fiscal VARCHAR(20),
    antecipado VARCHAR(20),
    desoneracao VARCHAR(20),
    percentual_diferimento VARCHAR(20),
    percentual_isencao VARCHAR(20),
    codigo_anp VARCHAR(20),
    codigo_beneficio VARCHAR(20),
    base_legal_icms VARCHAR(255),
    -- Controle
    revisado ENUM('sim','nao') DEFAULT 'nao',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    -- Restrição para garantir unicidade de EAN quando não for null
    UNIQUE KEY unique_ean (ean)
); 